### ISSUE TITLE
Enable code-compliance-check/Mend scan in kie-tools pipeline

### ISSUE THREAD

**Issue by gitgabrio** [IBM/kie-roadmap#100] opened 2023-05-03 10:48 UTC
Enable mend and compliance checks inside kie-tools pipeline. Ensure it scans only the four built modules

**Comment by baldimir** [comment] 2023-05-05 12:09
Closing this as a duplicate of https://github.com/IBM/kie-roadmap/issues/42

**Closed** 2023-05-29 11:56 UTC
Labels: area:cicd
